name: Build & Artifact

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@main
        with:
          esp_idf_version: v4.4
          target: esp32
          path: './'
      - name: Archive build output artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            build/flasher_args.json
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/config.bin
            build/www.bin
            build/OpenPyrojet.bin
            tools/flash.sh
#  finalize:
#      runs-on: ubuntu-latest
#      steps:
#        - name: Download Artifacts
#          uses: actions/download-artifact@master
#          with:
#            name: build
#            path: build
#        - name: Display structure of downloaded files
#          run: ls -R
#          working-directory: build/
