# This is a esp idf workflow to build ESP32 based project

name: Build and Artifact the ESP-IDF Project

# Controls when the action will run.
on:
  # Triggers the workflow on tag create like v1.0, v2.0.0 and so on
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@main
        with:
          esp_idf_version: v4.4
          target: esp32s2
          path: './'
